name: conan

on:
  pull_request:
  push:

jobs:
  create:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install tool dependencies
      run: |
        python3 -m pip install conan
    - uses: actions/checkout@v3
    - name: Configure profile
      run: |
        conan profile detect --name=default --force
    - name: Create package
      run: |
        conan create . --build=missing -pr:b=default
