name: linux

on:
  pull_request:
  push:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Install tool dependencies
      run: |
        python3 -m pip install conan
    - uses: actions/checkout@v3
    - name: Configure profile
      run: |
        conan profile new default --detect
    - name: Create package
      run: |
        conan create . --build=missing -pr:b=default
