name: windows

on:
  pull_request:
  push:

jobs:
  create:
    runs-on: windows-latest
    steps:
    - name: Install tool dependencies
      run: |
        choco install conan
    - uses: actions/checkout@v3
    - name: Configure profile
      run: |
        $env:Path += ';C:\Program Files\Conan\conan'
        conan profile new default --detect
    - name: Create package
      run: |
        $env:Path += ';C:\Program Files\Conan\conan'
        $env:Path += ';C:\Program Files\Meson'
        conan create . --build=missing -pr:b=default

